### ISSUE TITLE
As an admin, I want to know who the current user is

### ISSUE THREAD

**Issue by kjpap** [bdleavitt/chatgpt-on-azure#10]
### This issue is for a: (mark with an `x`)
```
[ ] bug report -> please search issues before submitting
[x] feature request
[ ] documentation issue or request
[ ] regression (a behavior that used to work and stopped in a new release)
```
### Description
> As an admin, I want to know who the current user is so that I can have traceability into logging (#9 ) and see only my chats (#5 )

### Expected/desired behavior
Please include any acceptance criteria here (should look like tasks to complete for the issue to be resolved)
- [x] I can get the AAD guid for the signed in user from Azure Active Directory.

* If the user is already logged into the webapp and the auth header is available, use that. 
* Give me a way to do local dev. 
* The login should NOT be the app service managed identity,  but the user. 
* If the user is not already logged into the webapp, redirect to login screen. 

### Mention any other details that might be useful
> This may be a prereq for #5 and #9

**Comment by kjpap** [comment]
AAD integration is in there, but want to make sure that cascades to cosmos partitions, etc...

**Comment by bdleavitt** [comment]
Added utils for auth that can be used on the front end or the backend. 

- frontend/src/auth/authUtils.tsx 
- backend/auth/auth_utils.py (from auth.auth_utils import get_authenticated_user_details)
