### ISSUE TITLE
As a user, I want to have a chat UI that I can casually interact with chatGPT models (vanilla chat, no search)

### ISSUE THREAD

**Issue by bdleavitt** [bdleavitt/chatgpt-on-azure#13]
### This issue is for a: (mark with an `x`)
```
[ ] bug report -> please search issues before submitting
[x] feature request
[ ] documentation issue or request
[ ] regression (a behavior that used to work and stopped in a new release)
```

### Description
Need to create a UI and update flask app with update routes to have a "vanilla" chatGPT experience using. 

### Expected/desired behavior
- [x] User can click to a ChatGPT screen in the UI
- [x] User can submit a message to chatGPT
- [x] The user submission will successfully be passed as a properly formed "chat/completions" style message and conversation history. 
- [x] The model will respond back, and will be added to the conversation flow in the UI.

**Comment by kjpap** [comment]
@bdleavitt - is this complete with PR #16 ? Should we close out?
