### ISSUE TITLE
Create a "debug.ps1" file to run the frontend and falsk backend separately for local dev

### ISSUE THREAD

**Issue by bdleavitt** [bdleavitt/chatgpt-on-azure#31]
### This issue is for a: (mark with an `x`)
```
[ ] bug report -> please search issues before submitting
[x] feature request (including template changes)
[ ] documentation issue or request
[ ] regression (a behavior that used to work and stopped in a new release)
```

## Description is: 
If you want to speed up local development, you can run the code as...
Frontend: 
* navigate to app/frontend
* npm run dev (this will start the VITE server in debug mode, which will hot reload when frontend code changes. 

Backend 
* navigate to ./app
* run ./debug.ps1

**Comment by azeltov** [comment]
added debug script for ps1 and sh.
