### ISSUE TITLE
As a user, I want to see a history list of my distinct chats

### ISSUE THREAD

**Issue by kjpap** [bdleavitt/chatgpt-on-azure#5]
### This issue is for a: (mark with an `x`)
```
[ ] bug report -> please search issues before submitting
[x] feature request
[ ] documentation issue or request
[ ] regression (a behavior that used to work and stopped in a new release)
```

### Description
> As a user, I want to have my chats saved so that I am able to persist them across client sessions

<img width="259" alt="image" src="https://user-images.githubusercontent.com/20328489/234171254-d63430ac-b9b6-4b6d-a799-515ef6b61549.png">

Predecessor feature: #13 

### Expected/desired behavior
- [x] Show the conversations in a left panel for the user to be able to select and have the conversation be the active chat window
- [x] Should have helpful (short) description (probably GPT-generated) of what the chat is about
- [x] Pull the conversations from CosmosDB for that user
- [x] Should only be able to see *my* conversations (not able to see other users - i.e. authenticated user only)

### Mention any other details that might be useful
>  Ability to delete chat is not included in this feature

### Design / Wiki References
[Chat History Objects in NoSQL CosmosDB](https://github.com/bdleavitt/chatgpt-on-azure/wiki/Chat-History-objects-in-nosql-cosmos--%235)

**Comment by bdleavitt** [comment]
Will need to decide how to create the cosmsodb object schema for history objects in the CosmosDB https://github.com/bdleavitt/chatgpt-on-azure/wiki/Chat-History-objects-in-nosql-cosmos--%235

**Comment by bdleavitt** [comment]
Closed.
